resources:
- repo: self
  clean: true
queue:
  name: Hosted VS2017
  demands: msbuild

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.3.0'


- task: MSBuild@1
  displayName: 'Build solution JsonRpcSharp.sln'
  inputs:
    solution: JsonRpcSharp.sln

    msbuildArguments: '/t:restore;build /p:Configuration=Release'


- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack

    packagesToPack: build/JsonRpcSharp.nuspec

    packDestination: build

    versioningScheme: byBuildNumber


- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: build

    Contents: '*.nupkg'

    TargetFolder: '$(build.artifactstagingdirectory)'


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'


